# Generated by Django 5.0.6 on 2026-06-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical display name, e.g. 'HSBC'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Canonical rate type code, e.g. 'MORTGAGE_30Y'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RawIngestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_file", models.CharField(max_length=512)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial (some rows rejected)"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("rows_read", models.IntegerField(default=0)),
                ("rows_inserted", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("rows_rejected", models.IntegerField(default=0)),
                ("error_summary", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Rate as a percentage value, e.g. 6.7500 for 6.75%.",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="The date this rate is/was in effect (business date, not ingestion time)."
                    ),
                ),
                (
                    "ingestion_timestamp",
                    models.DateTimeField(
                        help_text="When this specific observation was scraped/ingested from the source."
                    ),
                ),
                ("currency", models.CharField(blank=True, default="USD", max_length=8, null=True)),
                ("source_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("raw_response_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="rates.provider",
                    ),
                ),
                (
                    "rate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="rates.ratetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["provider", "rate_type", "-effective_date"],
                        name="idx_rate_provider_type_date",
                    ),
                    models.Index(fields=["effective_date"], name="idx_rate_effective_date"),
                    models.Index(fields=["ingestion_timestamp"], name="idx_rate_ingestion_ts"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rate",
            constraint=models.UniqueConstraint(
                fields=("provider", "rate_type", "effective_date"),
                name="uniq_provider_ratetype_effective_date",
            ),
        ),
    ]
